sources:
- name: xtest-json
  type: json
- name: api2-test
  type: api
  url: https://jsonplaceholder.typicode.com/todos
- delimiter: ','
  name: csv-test01
  type: csv
- delimiter: ','
  name: testi
  type: csv
