sources:
- connection:
    host: localhost
    port: 5432
  file_path: /path/to/file
  headers: {}
  name: test_csv
  params: {}
  tables:
  - table1
  - table2
  type: csv
  url: https://api.example.com/new_data
- connection:
    dbname: test_db
    host: localhost
    password: passwd
    port: 5432
    user: postgres
  file_path: ''
  headers: {}
  name: test_database
  params: {}
  tables:
  - customer
  type: database
  url: ''
