sources:
- file_path: data/sample.csv
  name: test_csv
  type: csv
- file_path: data/sample.json
  name: test_json
  type: json
- connection:
    host: localhost
    port: 5432
  file_path: /path/to/file
  headers: {}
  name: test2_api
  params: {}
  tables:
  - table1
  - table2
  type: api
  url: https://api.example.com/new_data
- connection:
    dbname: test_db
    host: localhost
    password: passwd
    port: 5432
    user: postgres
  name: test_database
  tables:
  - customer
  type: database
