sources:
- connection: {}
  delimiter: ','
  encoding: utf-8
  file_path: data/example.csv
  headers: {}
  name: csv-test1
  params: {}
  tables: []
  type: csv
  url: ''
- connection: {}
  encoding: utf-8
  file_path: data/example.json
  headers: {}
  name: json-test1
  params: {}
  tables: []
  type: json
  url: ''
- connection: {}
  delimiter: ','
  encoding: utf-8
  file_path: data/example.csv
  headers: {}
  name: csv-test12
  params: {}
  tables: []
  type: csv
  url: ''
