sources:
- name: csv-test-local
  type: csv
  file_source_type: local
  file_path: data/example.csv
  delimiter: ','
  encoding: utf-8
- name: csv-http-test
  type: csv
  file_source_type: http
  file_path: http://192.168.1.142/shared/example.csv
  delimiter: ','
  encoding: utf-8
- name: json-http-test
  type: json
  file_source_type: http
  file_path: http://192.168.1.142/shared/example.json
  encoding: utf-8
