sources:
- name: json-test
  type: json
  file_path: data/example.json
  encoding: utf-8
- name: db-test
  type: database
  db_type: postgresql
  host: localhost
  port: '5432'
  user: postgres
  password: passwd
  db_name: dvdrental
  tables:
  - customer
  queries:
  - name: test-query
    query: SELECT * FROM customer LIMIT 5;
- name: api-test
  type: api
  url: https://api.fxratesapi.com/latest
  headers: {}
  params: {}
- name: csv-test
  type: csv
  file_path: data/example.csv
  delimiter: ','
  encoding: utf-8
