sources:
- name: csv-test-local
  type: csv
  file_source_type: local
  file_path: data/example.csv
  delimiter: ','
  encoding: utf-8
- name: csv-http-test
  type: csv
  file_source_type: http
  file_path: http://192.168.1.142/shared/example.csv
  delimiter: ','
  encoding: utf-8
- name: json-http-test
  type: json
  file_source_type: http
  file_path: http://192.168.1.142/shared/example.json
  encoding: utf-8
- name: api-test
  type: api
  url: https://api.fxratesapi.com/latest
  headers: {}
  params:
    base: USD
    rates: rates_BRL
    currencies: BRL,EUR
- name: json-test-local
  type: json
  file_source_type: local
  file_path: data/example.json
  encoding: utf-8
- name: db-psql-test
  type: database
  db_type: postgresql
  host: localhost
  port: '5432'
  user: postgres
  password: passwd
  db_name: dvdrental
  tables: []
  queries:
  - name: default1
    query: SELECT * FROM customer;
