sources:
- name: db-test
  type: database
  db_type: postgresql
  host: localhost
  port: '5432'
  user: postgres
  password: passwd
  db_name: dvdrental
  tables: []
  queries:
  - name: default-query
    query: SELECT * FROM customer;
